# Generated by Django 2.2.5 on 2021-05-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='区')),
            ],
            options={
                'verbose_name': '区',
                'verbose_name_plural': '区',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Address', verbose_name='区')),
            ],
            options={
                'verbose_name': '分布区域',
                'verbose_name_plural': '分布区域',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='市')),
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='作物名')),
            ],
            options={
                'verbose_name': '危害作物',
                'verbose_name_plural': '危害作物',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='科名称')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='科代码')),
            ],
            options={
                'verbose_name': '科',
                'verbose_name_plural': '科',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='属名称')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='属代码')),
            ],
            options={
                'verbose_name': '属',
                'verbose_name_plural': '属',
            },
        ),
        migrations.CreateModel(
            name='Lonlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.TextField(verbose_name='经度')),
                ('latitude', models.TextField(verbose_name='纬度')),
            ],
            options={
                'verbose_name': '经纬度',
                'verbose_name_plural': '经纬度',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='目名称')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='目代码')),
            ],
            options={
                'verbose_name': '目',
                'verbose_name_plural': '目',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='省')),
            ],
            options={
                'verbose_name': '省',
                'verbose_name_plural': '省',
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='害虫名称')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='害虫代码')),
                ('Latin', models.CharField(blank=True, max_length=255, unique=True, verbose_name='拉丁名称')),
                ('egg', models.DateField(verbose_name='卵时期')),
                ('larva', models.DateField(verbose_name='幼虫/若虫时期')),
                ('pupa', models.DateField(blank=True, verbose_name='蛹时期')),
                ('adult', models.DateField(verbose_name='成虫时期')),
                ('encyclopedias', models.TextField(blank=True, null=True, verbose_name='百科')),
                ('areas', models.ManyToManyField(to='pest.Area', verbose_name='分布区域')),
                ('crops', models.ManyToManyField(blank=True, to='pest.Crop', verbose_name='危害作物')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Family', verbose_name='科')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Genus', verbose_name='属')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Orders', verbose_name='目')),
            ],
            options={
                'verbose_name': '害虫列表',
                'verbose_name_plural': '害虫列表',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.City', verbose_name='市'),
        ),
        migrations.AddField(
            model_name='area',
            name='lonlat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Lonlat', verbose_name='经纬度'),
        ),
        migrations.AddField(
            model_name='area',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest.Province', verbose_name='省'),
        ),
    ]
